name: Build and Release

on:
  push:
    branches: [ master ]

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Fix permissions and build
        run: |
          chmod +x gradlew
          
          # Простая сборка
          ./gradlew build -x test

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: build-${{ github.run_number }}
          name: "Build #${{ github.run_number }}"
          body: |
            Автоматическая сборка
            Номер: #${{ github.run_number }}
            Коммит: ${{ github.sha }}
          files: |
            build/libs/*.jar
            start.bat